name: DEPLOY

on:
  workflow_dispatch:
    inputs:
      deployNotes:
        description: '手动触发部署'
        required: true
        type: boolean
  push:
    branches: ['main']
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to aliyun
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install and build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g corepack zx
          corepack enable
          node -v
          npm -v
          pnpm -v
          zx -v
          chmod +x ./scripts/deploy.js
          pnpm install
          pnpm run semantic-release
